FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir fastapi uvicorn[standard] pandas numpy scikit-learn joblib

COPY research_centers.csv .
COPY app.py .
# Pre-built model artifact (generated by EDA_and_Model.ipynb)
COPY cluster_model.pkl* ./

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
